# -*- coding: utf-8 -*-
"""Prosperity Trader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nd3_cqqkAb5TXXnoEkfRMvdHrDcIS4XQ
"""

import json
from datamodel import Listing, Observation, Order, OrderDepth, ProsperityEncoder, Symbol, Trade, TradingState
from typing import Any

class Logger:
    def __init__(self) -> None:
        self.logs = ""
        self.max_log_length = 3750

    def print(self, *objects: Any, sep: str = " ", end: str = "\n") -> None:
        self.logs += sep.join(map(str, objects)) + end

    def flush(self, state: TradingState, orders: dict[Symbol, list[Order]], conversions: int, trader_data: str) -> None:
        base_length = len(self.to_json([
            self.compress_state(state, ""),
            self.compress_orders(orders),
            conversions,
            "",
            "",
        ]))

        # We truncate state.traderData, trader_data, and self.logs to the same max. length to fit the log limit
        max_item_length = (self.max_log_length - base_length) // 3

        print(self.to_json([
            self.compress_state(state, self.truncate(state.traderData, max_item_length)),
            self.compress_orders(orders),
            conversions,
            self.truncate(trader_data, max_item_length),
            self.truncate(self.logs, max_item_length),
        ]))

        self.logs = ""

    def compress_state(self, state: TradingState, trader_data: str) -> list[Any]:
        return [
            state.timestamp,
            trader_data,
            self.compress_listings(state.listings),
            self.compress_order_depths(state.order_depths),
            self.compress_trades(state.own_trades),
            self.compress_trades(state.market_trades),
            state.position,
            self.compress_observations(state.observations),
        ]

    def compress_listings(self, listings: dict[Symbol, Listing]) -> list[list[Any]]:
        compressed = []
        for listing in listings.values():
            compressed.append([listing["symbol"], listing["product"], listing["denomination"]])

        return compressed

    def compress_order_depths(self, order_depths: dict[Symbol, OrderDepth]) -> dict[Symbol, list[Any]]:
        compressed = {}
        for symbol, order_depth in order_depths.items():
            compressed[symbol] = [order_depth.buy_orders, order_depth.sell_orders]

        return compressed

    def compress_trades(self, trades: dict[Symbol, list[Trade]]) -> list[list[Any]]:
        compressed = []
        for arr in trades.values():
            for trade in arr:
                compressed.append([
                    trade.symbol,
                    trade.price,
                    trade.quantity,
                    trade.buyer,
                    trade.seller,
                    trade.timestamp,
                ])

        return compressed

    def compress_observations(self, observations: Observation) -> list[Any]:
        conversion_observations = {}
        for product, observation in observations.conversionObservations.items():
            conversion_observations[product] = [
                observation.bidPrice,
                observation.askPrice,
                observation.transportFees,
                observation.exportTariff,
                observation.importTariff,
                observation.sunlight,
                observation.humidity,
            ]

        return [observations.plainValueObservations, conversion_observations]

    def compress_orders(self, orders: dict[Symbol, list[Order]]) -> list[list[Any]]:
        compressed = []
        for arr in orders.values():
            for order in arr:
                compressed.append([order.symbol, order.price, order.quantity])

        return compressed

    def to_json(self, value: Any) -> str:
        return json.dumps(value, cls=ProsperityEncoder, separators=(",", ":"))

    def truncate(self, value: str, max_length: int) -> str:
        if len(value) <= max_length:
            return value

        return value[:max_length - 3] + "..."

logger = Logger()

class Trader:
    def run(self, state: TradingState) -> tuple[dict[Symbol, list[Order]], int, str]:
        result = {}
        conversions = 0

        def getMean(product):
            order_depth : OrderDepth = state.order_depths[product]

            sell_list = list(order_depth.sell_orders.items())
            buy_list = list(order_depth.buy_orders.items())

            if len(sell_list) != 0:
                ask, _ = sell_list[0]
            else:
                ask = None
            if len(buy_list) == 0:
                bid, _ = buy_list[0]
            else:
                bid = None

            if ask:
                return 0.5 * (ask + bid) if bid else ask
            else:
                return bid if bid else None

        def order(product, mean, scale):

            order_depth : OrderDepth = state.order_depths[product]
            orders: List[Order] = []

            position = state.position.get(product, 0)

            if len(order_depth.sell_orders) != 0:
                new_pos = position
                items = list(order_depth.sell_orders.items())
                for best_ask, best_ask_amount in items:
                    target = int((mean - best_ask) * scale)
                    target = min(target, 20)
                    if target > new_pos:

                        amount = min(target - new_pos, -best_ask_amount)
                        orders.append(Order(product, best_ask, amount))
                        new_pos += amount

                    else:
                        break

            if len(order_depth.buy_orders) != 0:
                new_pos = position
                items = list(order_depth.buy_orders.items())
                for best_bid, best_bid_amount in items:
                    target = int((mean - best_bid) * scale)
                    target = max(target, -20)
                    if target < new_pos:

                        amount = max(target - new_pos, -best_bid_amount)
                        orders.append(Order(product, best_bid, amount))
                        new_pos += amount
                    else:
                        break

            return orders

        trader_data = state.traderData
        if trader_data:
            mean_starfruit = int(trader_data)
        elif getMean('STARFRUIT'):
            mean_starfruit = getMean('STARFRUIT')
            trader_data = str(mean_starfruit)
        else:
            mean_starfruit = 5000

        result['STARFRUIT'] = order('STARFRUIT', mean_starfruit, 1)
        result['AMETHYSTS'] = order('AMETHYSTS', 10000, 8)

        logger.flush(state, result, conversions, trader_data)
        return result, conversions, trader_data